name: iOS CI Build (Tuist + Secrets)

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install Mise and Tuist
        run: |
          curl -fsSL https://mise.jdx.dev/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"
          mise install tuist
          mise use -g tuist

      - name: Generate xcconfig
        run: |
          mkdir -p SupportingFiles
          echo "BASE_URL = ${BASE_URL}" > SupportingFiles/Secrets.xcconfig
        env:
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Generate Xcode project with Tuist
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          mise exec -- tuist install
          mise exec -- tuist generate --no-open

      - name: Build with xcodebuild
        run: |
          set -o pipefail
          xcodebuild \
            -workspace Bitnagil.xcworkspace \
            -scheme App \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            clean build | xcpretty

